Fix various bugs
MLG-Fortress/PrettySimpleShop pull request #7
Opened 2019-01-04 16:18 UTC by Nashoba24

If a player executes /ec (Essentials) the 2 following stack traces appear. I know that a try catch isn't very clean but this is the only way I found without using NMS.
`Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_13_R2.InventoryEnderChest.getLocation(InventoryEnderChest.java:18) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftInventory.getLocation(CraftInventory.java:488) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at com.robomwm.prettysimpleshop.shop.ShopListener.onOpenInventory(ShopListener.java:203) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor359.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	... 26 more`
`Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_13_R2.InventoryEnderChest.getLocation(InventoryEnderChest.java:18) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftInventory.getLocation(CraftInventory.java:488) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at com.robomwm.prettysimpleshop.shop.ShopListener.onClose(ShopListener.java:259) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor347.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	... 16 more`

I also fixed this error:
`java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.block.CraftShulkerBox cannot be cast to org.bukkit.block.Chest
	at com.robomwm.prettysimpleshop.feature.ShowoffItem$2.run(ShowoffItem.java:188) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

2019-01-04 16:50 UTC, RoboMWM commented
Use three backticks to make a code block. I've fixed it for you. Also, it seems your first stacktrace is cut off. And try to copy from logs, you have some weird spacing in them.

2019-01-04 16:54 UTC, RoboMWM commented
As for ender chests, I thought I already had an NPE check for this. If it's null, then it definitely is something that the plugin shouldn't care about. (And in the case of ender chests this should be the case, or at least for those opened without a corresponding block.)

It seems that spigot doesn't like this behavior - I think Paper does this properly though and returns null as necessary. getLocation should return null as per javadocs. I believe you should report this issue with spigot if these errors don't appear in paper(?)

2019-01-04 16:58 UTC, RoboMWM requested changes
Pretty good, just some minor things. But we need to investigate why this is happening first.

2019-01-04 16:58 UTC, RoboMWM commented on src/main/java/com/robomwm/prettysimpleshop/shop/ShopListener.java
> +
???

2019-01-04 16:58 UTC, RoboMWM commented on src/main/java/com/robomwm/prettysimpleshop/shop/ShopListener.java
> +        try {
I prefer newline braces here for consistency.

2019-01-04 16:58 UTC, RoboMWM commented on src/main/java/com/robomwm/prettysimpleshop/shop/ShopListener.java
> +        catch (NullPointerException e) {
Should probably add a code comment stating this is a spigot/custom inventory bug. Perhaps reference whatever bug report when you make it.

2019-01-04 17:00 UTC, RoboMWM commented
Also, try to keep each fix in a different PR. Don't lump "fixes" all in one PR.

As for the inventory thing - may also be an Essentials thing. Not sure how it's opening the enderchest to the user.

2019-01-04 17:03 UTC, RoboMWM commented on src/main/java/com/robomwm/prettysimpleshop/shop/ShopListener.java
> +        catch (NullPointerException e) {
Also, did you indent with tabs or something? Spaces please.

2019-01-04 17:06 UTC, RoboMWM commented
Yea, supposed to return null. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/Inventory.html#getLocation--

I guess spigot needs to wrap their call in a try-catch?

2019-01-04 17:30 UTC, niqore commented on src/main/java/com/robomwm/prettysimpleshop/shop/ShopListener.java
> +
I just tried something else before then removed an import... And git detected a difference

2019-01-04 19:03 UTC, RoboMWM commented
Anyways, try testing Inventory#getLocation with your own plugin that opens an ender chest (or any custom inventory for that matter) and see if you also get an NPE. Would like to know if this is indeed a spigot issue.

2019-01-04 19:03 UTC, RoboMWM approved these changes

2019-02-28 20:18 UTC, RoboMWM commented
@Nashoba24 have you followed up on this? 

I wonder if the enderchest thing has to do with spigot altering how custom inventories are created. I think I resolved a similar issue in another plugin, will check now.

2019-02-28 20:20 UTC, RoboMWM commented
Ah, it probably has to do with stripping away the custom inventoryholder. https://github.com/MLG-Fortress/CustomItemRecipes/commit/eeb826cfe235ece7abe0b53cf408f123934aa0ad

Either way, spigot needs to fix this and return null instead of asking NMS and having that throw an exception.

2019-02-28 20:29 UTC, merged

2019-02-28 20:29 UTC, RoboMWM commented
@Nashoba24 Please confirm if this issue still exists. If so, then please report the bug to the spigot JIRA.